# Barre d'état stylisée
set -g status-style fg=white
set -g status-left "#[fg=white] ❮ #[fg=white]#S #[fg=white]❯"
set -g status-right "#[fg=white] ❮ #[fg=white]RAM: #(~/scripts/ram_usage.sh) | %H:%M:%S | %d-%m-%Y #[fg=white]❯"

# Activer la souris
set -g mouse on

# Activer TPM et un thème
set -g @plugin 'dracula/tmux'

# === Navigation de panneaux avec hjkl (préfix + hjkl) ===
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# === Redimensionner panneaux (préfix + maj + hjkl) ===
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# === Reload config rapidement ===
bind r source-file ~/.tmux.conf \; display-message "Config reload 🚀"
